### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by sethcenterbar** [dokklib/dokklib-db#6]
https://dokklib.com/libs/db/ is currently down. 

I have some questions about setting this up for local development, but I imagine some of this may be in that documentation. 

Specifically, I'm a bit confused on how dokklib-db knows how to speak to dynamo. I'm assuming that's handled through boto3, but I can't seem to get past the ResourceNotFoundException. Either way, I think it would be nice to include the boto3 setup in the getting started guide on the github page.

**Comment by gricey432** [comment]
Looks like the website is now being used for adware distribution

**Comment by kbakk** [comment]
@agostbiro you may want to address this, you're linking to this website from https://github.com/pynamodb/PynamoDB/issues/686 and it is confusing.

**Comment by agostbiro** [comment]
## Re domain:

Thanks for @kbakk and for all the other comments I somehow missed prior notifications. Covid happened just as I released this project and had to abandon it unfortunately. 

The domain has expired, but I've updated links to point to Github and marked the project as officially **deprecated.**

## Re credentials:

@sethcenterbar you're right, the project [uses boto3](https://github.com/dokklib/dokklib-db/blob/3665775c6d369ca08431b5295c1c181a9dca97cd/dokklib_db/table.py#L118) under the hood and credentials are expected to be provided via environment variables or via the other boto3 contextual [credentials configs.](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#environment-variables) If you're getting resource not found errors, a common cause is querying the wrong region. When in doubt you can always use the AWS CLI in the same shell where you run the Python source to debug as they'll use the same credentials.
